#server:
#  port: 8191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rent
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bvrsilva1/spring-cloud-config-rent
          search-paths:
           - '*service'



